[2024-05-27T00:32:11.565+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-27T00:32:11.576+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_python_operator_v06.get_name manual__2024-05-27T00:27:10.608977+00:00 [queued]>
[2024-05-27T00:32:11.579+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_python_operator_v06.get_name manual__2024-05-27T00:27:10.608977+00:00 [queued]>
[2024-05-27T00:32:11.579+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 6
[2024-05-27T00:32:11.583+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_name> on 2024-05-27 00:27:10.608977+00:00
[2024-05-27T00:32:11.586+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=12341) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-27T00:32:11.586+0000] {standard_task_runner.py:63} INFO - Started process 12342 to run task
[2024-05-27T00:32:11.586+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_python_operator_v06', 'get_name', 'manual__2024-05-27T00:27:10.608977+00:00', '--job-id', '208', '--raw', '--subdir', 'DAGS_FOLDER/create_dag_python_operator_2.py', '--cfg-path', '/tmp/tmpggeox4fz']
[2024-05-27T00:32:11.587+0000] {standard_task_runner.py:91} INFO - Job 208: Subtask get_name
[2024-05-27T00:32:11.601+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_python_operator_v06.get_name manual__2024-05-27T00:27:10.608977+00:00 [running]> on host 6bbd6353fbe6
[2024-05-27T00:32:11.630+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gauti' AIRFLOW_CTX_DAG_ID='dag_python_operator_v06' AIRFLOW_CTX_TASK_ID='get_name' AIRFLOW_CTX_EXECUTION_DATE='2024-05-27T00:27:10.608977+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-27T00:27:10.608977+00:00'
[2024-05-27T00:32:11.630+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-27T00:32:11.641+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-27T00:32:11.642+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-27T00:32:11.644+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_python_operator_v06, task_id=get_name, run_id=manual__2024-05-27T00:27:10.608977+00:00, execution_date=20240527T002710, start_date=20240527T003211, end_date=20240527T003211
[2024-05-27T00:32:11.689+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-27T00:32:11.697+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-27T00:32:11.698+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
