[2024-05-24T08:24:03.256+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-24T08:24:03.271+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag.first_task scheduled__2024-05-13T00:00:00+00:00 [queued]>
[2024-05-24T08:24:03.274+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag.first_task scheduled__2024-05-13T00:00:00+00:00 [queued]>
[2024-05-24T08:24:03.274+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-05-24T08:24:03.280+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): first_task> on 2024-05-13 00:00:00+00:00
[2024-05-24T08:24:03.284+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=946) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-24T08:24:03.283+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag', 'first_task', 'scheduled__2024-05-13T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmppt8fuiho']
[2024-05-24T08:24:03.285+0000] {standard_task_runner.py:63} INFO - Started process 949 to run task
[2024-05-24T08:24:03.285+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask first_task
[2024-05-24T08:24:03.309+0000] {task_command.py:426} INFO - Running <TaskInstance: our_first_dag.first_task scheduled__2024-05-13T00:00:00+00:00 [running]> on host 6bbd6353fbe6
[2024-05-24T08:24:03.360+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gauti' AIRFLOW_CTX_DAG_ID='our_first_dag' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-13T00:00:00+00:00'
[2024-05-24T08:24:03.362+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-24T08:24:03.383+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-24T08:24:03.386+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hello everyone, this is our first task!!!']
[2024-05-24T08:24:03.390+0000] {subprocess.py:86} INFO - Output:
[2024-05-24T08:24:03.391+0000] {subprocess.py:93} INFO - hello everyone, this is our first task!!!
[2024-05-24T08:24:03.392+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-24T08:24:03.393+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-24T08:24:03.407+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=our_first_dag, task_id=first_task, run_id=scheduled__2024-05-13T00:00:00+00:00, execution_date=20240513T000000, start_date=20240524T082403, end_date=20240524T082403
[2024-05-24T08:24:03.424+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-24T08:24:03.436+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-24T08:24:03.439+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
