[2024-05-27T00:32:12.436+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-27T00:32:12.448+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_python_operator_v06.get_name manual__2024-05-27T00:27:11.755055+00:00 [queued]>
[2024-05-27T00:32:12.451+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_python_operator_v06.get_name manual__2024-05-27T00:27:11.755055+00:00 [queued]>
[2024-05-27T00:32:12.452+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 6
[2024-05-27T00:32:12.456+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_name> on 2024-05-27 00:27:11.755055+00:00
[2024-05-27T00:32:12.459+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=12344) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-27T00:32:12.459+0000] {standard_task_runner.py:63} INFO - Started process 12345 to run task
[2024-05-27T00:32:12.459+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_python_operator_v06', 'get_name', 'manual__2024-05-27T00:27:11.755055+00:00', '--job-id', '210', '--raw', '--subdir', 'DAGS_FOLDER/create_dag_python_operator_2.py', '--cfg-path', '/tmp/tmptq85uj4p']
[2024-05-27T00:32:12.460+0000] {standard_task_runner.py:91} INFO - Job 210: Subtask get_name
[2024-05-27T00:32:12.476+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_python_operator_v06.get_name manual__2024-05-27T00:27:11.755055+00:00 [running]> on host 6bbd6353fbe6
[2024-05-27T00:32:12.509+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gauti' AIRFLOW_CTX_DAG_ID='dag_python_operator_v06' AIRFLOW_CTX_TASK_ID='get_name' AIRFLOW_CTX_EXECUTION_DATE='2024-05-27T00:27:11.755055+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-27T00:27:11.755055+00:00'
[2024-05-27T00:32:12.509+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-27T00:32:12.522+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-27T00:32:12.523+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-27T00:32:12.525+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_python_operator_v06, task_id=get_name, run_id=manual__2024-05-27T00:27:11.755055+00:00, execution_date=20240527T002711, start_date=20240527T003212, end_date=20240527T003212
[2024-05-27T00:32:12.558+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-27T00:32:12.565+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-27T00:32:12.566+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
